### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by Nadery** [Shopify/polaris-icons#663]
### Slack handle

@yourslackhandle

### Original icon name

arrow down (minor)

### When would you like it by?

DD/MM/YYYY

### Updated icon SVG

```xml
<svg xmlns="http://www.w3.org/2000/svg" ...
```

### Icon metadata (optional)

```yml
name: arrow down
set: major or minor
description:
  # Description:
  #
  #   Action: "Used to denote <x action>"
  #   Wayfinding: "Used to help direct merchants to <x>"
  #   Concept: "Used to represent <x>"
  #   Education: "Used to give merchants more information about <context x>"
  #
  # Full guidelines: https://bit.ly/2GdMpmg
  #
  # (delete this comment block)
  N/A
keywords:
  # - synonym
  # - another synonym
  # - related shape or symbol
  # (delete this comment block)
  - N/A
authors:
  # - Sasha Oliveira
  # - Co-author’s name (optional)
  # (delete this comment block)
  - N/A
# Optional: fill exclusive_use if the icon should *only* be used
# in specific areas of the admin (such as “Orders”):
exclusive_use:
```
